### ISSUE TITLE
maybe rename to "chipotle"? 😂

### ISSUE THREAD

**Issue by orzklv** [crystalnyan/cple#1]
look how delicious is chipotle 🤤
![image](https://github.com/crystalnyan/cple/assets/54666588/9b0697ee-f5c0-43aa-9df3-8f916a76a280)

**Comment by ubranch** [comment]
народ нас всех зачипотетили

**Comment by murodovazizmurod** [comment]
good idea!

**Comment by tapnisu** [comment]
chipotle

**Comment by orzklv** [comment]
@crystalnyan assistance needed for shipping this idea!

**Comment by BlackArcheruz** [comment]
Chipotle ⚔️
